[build]
  publish = "dist"
  command = "cp customNodeModules/vite-plugin-admin-dashboard.js node_modules/astro-netlify-cms/dist/vite-plugin-admin-dashboard.js && npm run build"
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"